disabled: false
reporter:
  logSpans: false
  localAgentHostPort: "jaeger-agent:6831"
  queueSize: 1000000
  bufferFlushInterval: 10
sampler:
  type: "probabilistic"
  param: 0.1
otel:
  endpoint: "otel-collector.default.svc.cluster.local:4317"